In [ ]:
# Input the names and ages of two people
name1 = input("Enter the name of the first person: ")
age1 = int(input("Enter the age of the first person: "))

name2 = input("Enter the name of the second person: ")
age2 = int(input("Enter the age of the second person: "))

# Print out the output
print("First person:")
print("Name:", name1)
print("Age:", age1)

print("\nSecond person:")
print("Name:", name2)
print("Age:", age2)

Enter the name of the first person: khiran
Enter the age of the first person: 19
Enter the name of the second person: rahul
Enter the age of the second person: 36
First person:
Name: khiran
Age: 19

Second person:
Name: rahul
Age: 36

In [ ]:
# Input the numbers
num_list = input("Enter a list of numbers (separated by space): ").split()

# Convert the input numbers to integers
num_list = [int(num) for num in num_list]

# Calculate the average
average = sum(num_list) / len(num_list)

# Print the average
print("The average is:", average)

Enter a list of numbers (separated by space): 1 2 3 4 5 6 7 8 9
The average is: 5.0

In [ ]:
# Input the dimensions of the rectangle
length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))

# Calculate the area
area = length * width

# Print the area
print("The area of the rectangle is:", area)

Enter the length of the rectangle: 9
Enter the width of the rectangle: 5
The area of the rectangle is: 45.0

In [ ]:
# Input the limit
limit = int(input("Enter the limit: "))

# Initialize sum variable
sum_of_numbers = 0

# Calculate the sum of natural numbers
for num in range(1, limit + 1):
    sum_of_numbers += num

# Print the sum
print("The sum of natural numbers up to", limit, "is:", sum_of_numbers)

Enter the limit: 5
The sum of natural numbers up to 5 is: 15

In [ ]:
import math

# Input the numbers
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Calculate the HCF
hcf = math.gcd(num1, num2)

# Print the HCF
print("The HCF of", num1, "and", num2, "is:", hcf)

Enter the first number: 8
Enter the second number: 5
The HCF of 8 and 5 is: 1

In [ ]:
# Input the number
num = int(input("Enter a number: "))

# Initialize factorial variable
factorial = 1

# Calculate the factorial
if num < 0:
    print("Factorial is not defined for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    for i in range(1, num + 1):
        factorial *= i

    # Print the factorial
    print("The factorial of", num, "is:", factorial)

Enter a number: 9
The factorial of 9 is: 362880

In [ ]:
def pypart(n):
    for i in range(0, n):
        for j in range(0, i+1):
            print("* ",end="")
        print("\r")
n = 10
pypart(n)

*
* *
* * *
* * * *
* * * * *
* * * * * *
* * * * * * *
* * * * * * * *
* * * * * * * * *
* * * * * * * * * *